# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
addons:
  apt:
    packages:
      - libgeos-dev
      - libgdal1-dev
      - libproj-dev
sudo: false
cache: packages
cran: https://cran.rstudio.com/
