# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - sudo add-apt-repository "deb ${CRAN}/bin/linux/ubuntu $(lsb_release -cs)/"
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
        - sudo add-apt-repository -y "ppa:marutter/rrutter"
        - sudo add-apt-repository -y "ppa:marutter/c2d4u"
        - sudo apt-get update -qq
        - sudo apt-get install -y --no-install-recommends r-base-dev
        - sudo apt-get install httr xml2 purrr dplyr shiny rgdal digest
      script:
        - wget https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
        - sh -ex ./travis-tool.sh run_tests
