version: 2
jobs:
   build:
     docker:
       - image: rocker/geospatial:latest
     steps:
       - checkout
       - run: R CMD build .
       - run: R CMD check "kokudosuuchi_0.3.0.9000.tar.gz" --as-cran --no-manual
